### ISSUE TITLE
Image width 100% stretches IMG

### ISSUE THREAD

**Issue by ezkay** [ng2-ui/ng2-parallax-scroll#2]
As this is not using `background-size: cover;`, a small image leaves a blank space. If IMG is set with `width: 100%;`, the image is stretched..

Or maybe a solution with css like this one?
https://github.com/TheOriginalJosh/nativescript-ng2-parallax

**Comment by allenhwkim** [comment]
Question:
1. Do you want to stretch out image if smaller than box?
2. Do you have any working example?

**Comment by ezkay** [comment]
Oh shoot, just forgot to hook the image in.
The screenshot shows two parallax containers. The upper one has an image that is big enough. The second image is too small. So it lefts whitespace.Setting the width to 100% leaves the height untouched so that the proportions would be broken.
![bildschirmfoto 2016-11-17 um 19 35 20](https://cloud.githubusercontent.com/assets/10404121/20716525/d2c21fc8-b652-11e6-8e00-04d32b9cc90f.png)

**Comment by allenhwkim** [comment]
Thank you for more explanation
I will see what I can do about it.
Meanwhile, any help or PR would be highly appreciated

**Comment by allenhwkim** [comment]
This is fixed already

**Comment by allenhwkim** [comment]
This is fixed already
