### ISSUE TITLE
Not an ngmodule ?

### ISSUE THREAD

**Issue by movrack** [ng2-ui/ng2-parallax-scroll#4]
Hi,
When I build the app I always get this message:

> ERROR in Unexpected value 'NguiParallaxScrollModule in C:/.../project/node_modules/@ngui/parallax-scroll/dist/parallax-scroll.module.d.ts' imported by the module 'AppModule in C:/.../project/src/app/app.module.ts'.
Please add a @NgModule annotation.

In app.module I do the import:

    import { NguiParallaxScrollModule } from '@ngui/parallax-scroll';
    @NgModule({
        ...
        imports: [NguiParallaxScrollModule ]                // Note: your line in your readme look not correct.
        ...
     })
     export class AppModule { }

Any idea ?
I use angular 4.

**Comment by allenhwkim** [comment]
Did you do npm install?
Please take a look at app directory for more.

If not working, please explain all steps what you did, or make a github repo. to reproduce this error.

**Comment by movrack** [comment]
I don't know what was my error but after multiple chang,e it's working know :)

**Comment by movrack** [comment]
In fact, it's not resolved.
When I run ng serve with the import it does"nt work.
If I removed the import from the file, run any command (serve, start, build, ...) the app work (without the parallax) and then, with the live reload, I can put back the import. This is working. But it's not a usable solution for production.

In facts, it's exactly the same error as this one:

https://github.com/ng2-ui/sticky/issues/5



For testing you can do this:

Install @angular/cli

    ng -v
    @angular/cli: 1.0.0
    ng new ngParallaxScrollTest
    cd ngParallaxScrollTest
    npm install @ngui/parallax-scroll --save

edit src/app/app.module.ts

        import { BrowserModule } from '@angular/platform-browser';
        import { NgModule } from '@angular/core';
        import { FormsModule } from '@angular/forms';
        import { HttpModule } from '@angular/http';
        import { NguiParallaxScrollModule } from '@ngui/parallax-scroll';

       import { AppComponent } from './app.component';

      @NgModule({
        declarations: [
          AppComponent
         ],
        imports: [
          BrowserModule,
          FormsModule,
          HttpModule,
          NguiParallaxScrollModule
        ],
        providers: [],
        bootstrap: [AppComponent]
      })
      export class AppModule { }

Run `ng serve` or `ng build`
And the error is here.
> ERROR in NguiParallaxScrollModule is not an NgModule

**Comment by allenhwkim** [comment]
Can you try this?
https://github.com/angular/angular-cli/issues/3426

`@asBrettisay, this worked for me. I was getting this error with ng2-flex-layout. Downgrading from angular-cli@1.0.0-beta.22 to angular-cli@1.0.0-beta.15 did the trick!`

`With angular-cli beta.24 and typescript 2.1.4 I got the same error, but when downgraded only the typescript to version 2.0.10 the error was gone.`

.... and more

There are so many variables with angular-cli, which I cannot make a fix.

Sharing your solution here would be a good idea.

**Comment by movrack** [comment]
Sorry, I take time to try it.
Since I use angular cli 1.0.0 with angular4 and typescript setted to 2.2.0 by default, I won't downgrade them.

If I found a solution, I will post it.

**Comment by allenhwkim** [comment]
It might be related to not having `.metadata.json`. I  will look into that matter also.

**Comment by allenhwkim** [comment]
complier-cli version also be a reason not to make `.metadata.json` files
    "@angular/compiler-cli": "^2.4.9",

**Comment by allenhwkim** [comment]
This has been updated and released as 0.5.1
